version: '2'

services:
  orderer.aeries.io:
    container_name: orderer.aeries.io
    image: hyperledger/fabric-orderer:x86_64-1.1.0
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/aeries.io/orderers/orderer.aeries.io/msp:/etc/hyperledger/msp/orderer/msp

  ca.org1.aeries.io:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.aeries.io

    ports:
      - 7071:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.aeries.io-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/e57b28a7aa5910b32eafdb06bc00f098055b50f635b923d82585b27c65b94c98_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.aeries.io/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.aeries.io

  peer0.org1.aeries.io:
    container_name: peer0.org1.aeries.io
    image: hyperledger/fabric-peer:x86_64-1.1.0
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.aeries.io
      - CORE_PEER_ADDRESS=peer0.org1.aeries.io:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artnetworkv2_org1_default
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdborg1peer0:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7052:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./channel:/opt/gopath/src/github.com/hyperledger/fabric
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org1.aeries.io/peers/peer0.org1.aeries.io/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org1.aeries.io/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.aeries.io
      - couchdborg1peer0

  peer1.org1.aeries.io:
    container_name: peer1.org1.aeries.io
    image: hyperledger/fabric-peer:x86_64-1.1.0
    environment:
      - CORE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.aeries.io
      - CORE_PEER_ADDRESS=peer1.org1.aeries.io:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artnetworkv2_org1_default
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdborg1peer1:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7053:7051
      - 7054:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./channel:/opt/gopath/src/github.com/hyperledger/fabric
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/org1.aeries.io/peers/peer1.org1.aeries.io/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/org1.aeries.io/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer.aeries.io
      - couchdborg1peer1

  couchdborg1peer0:
    container_name: couchdborg1peer0
    image: hyperledger/fabric-couchdb:x86_64-0.4.6
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db

  couchdborg1peer1:
    container_name: couchdborg1peer1
    image: hyperledger/fabric-couchdb:x86_64-0.4.6
    ports:
      - 5985:5984
    environment:
      DB_URL: http://localhost:5985/member_db
